# Generated by Django 5.1 on 2024-10-31 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(choices=[('CSE123', 'CSE123: Programming Fundamentals I '), ('CSE124', 'CSE124: Programming Fundamentals II'), ('MATH307', 'MATH307: Differential Equations'), ('MATH308', 'MATH308: Linear Algebra'), ('ENGL204', 'ENGL204: Popular Fiction and Media')], max_length=35)),
                ('instructor', models.CharField(max_length=30)),
                ('lectureNum', models.IntegerField()),
                ('notes', models.TextField()),
            ],
        ),
    ]
