# Generated by Django 5.1 on 2024-11-07 23:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
        ('students', '0004_alter_student_minor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='notes',
            new_name='description',
        ),
        migrations.AlterField(
            model_name='note',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='written_notes', to='students.student'),
        ),
    ]
