# Generated by Django 5.1 on 2024-11-05 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='firstName',
        ),
        migrations.RemoveField(
            model_name='student',
            name='lastName',
        ),
        migrations.AddField(
            model_name='student',
            name='major',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='minor',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
