# Generated by Django 5.1 on 2024-11-05 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_alter_student_minor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='minor',
            field=models.CharField(blank=True, default=1, max_length=30),
            preserve_default=False,
        ),
    ]
