# Generated by Django 5.1 on 2024-11-07 22:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0003_alter_course_title'),
        ('students', '0004_alter_student_minor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscribed_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course')),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('subscribed_to', 'subscriber'), name='unqiue_subscription')],
            },
        ),
    ]
